server:
  port: 8080

spring:
  application:
    name: lesson
  datasource:
    username: 'admin'
    url: jdbc:postgresql://localhost:5432/lesson
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'