on: [push, pull_request]

jobs:
  deploy:
    name: Start
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Start
        run: docker-compose up -d

      - name: Check
        run:  localhost:8080/api/v1/lessons/all
